### ISSUE TITLE
compatibilty with fastai Version 2

### ISSUE THREAD

**Issue by JJashim** [sean-mcclure/defect_classifier#3]
Howto make it work with fastai version 2 ?
 -Facing error while performing load_learner in classifier.py. Please resolve. 

Can you please share the requirement.txt file..

**Comment by sean-mcclure** [comment]
What have you tried? 

Sean

**Comment by JJashim** [comment]
Hi Sean,

I tried to execute your code where i did find difficulties over the package conflicts esp. fastai. Hence, I couldn't execute it to the fullest. But, now it's resolved. Thanks. 
But adding up requirement.txt to your repo. would be of great help.

**Comment by sean-mcclure** [comment]
Clad it worked out. I added a requirements.txt file to the repo.
